### ISSUE TITLE
choose.From assignment mismatch

### ISSUE THREAD

**Issue by VSngg** [rwxrob/keg#47]
When installing both `keg@latest` and `kn@latest` I get the following error
```
go/pkg/mod/github.com/rwxrob/keg@v0.2.4/cmd.go:363:19: assignment mismatch: 3 variables but choose.From returns 2 values
```

**Comment by BuddhiLW** [comment]
If 
- I clone the repository,
- issue `go mod tidy`,
- issue `go build cmd/keg/main.go`
- move the `main` compiled artifact to `~/.local/bin/kg`

It then works fine.

For some reason, before you have all the modules installed, `choose.From(hits.PrettyLines())` understand the return value as two-valued. As, after all modules install, it understands it as three-valued return (insuring the build).


The error happens here, in the choose.From() assignment, on the **default** switch:

```go
	Call: func(x *Z.Cmd, args ...string) error {
		if !term.IsInteractive() {
			return titleCmd.Call(x, args...)
		}
		keg, err := current(x.Caller)
		if err != nil {
			return err
		}
		id := args[0]
		if id == "last" {
			if n := Last(keg.Path); n != nil {
				id = n.ID()
			}
		} else {
			_, err := strconv.Atoi(id)
			if err != nil {
				dex, err := ReadDex(keg.Path)
				if err != nil {
					return err
				}
				key := strings.Join(args, " ")
				hits := dex.WithTitleText(key)
				switch len(hits) {
				case 1:
					id = strconv.Itoa(hits[0].N)
				case 0:
					return fmt.Errorf("no titles match: %v", key)
				default:
					i, _, err := choose.From(hits.PrettyLines())
					if err != nil {
						return err
					}
					if i < 0 {
						return nil
					}
					id = strconv.Itoa(hits[i].N)
				}
			}
		}
		path := filepath.Join(keg.Path, id, `README.md`)
		if !fs.Exists(path) {
			return fmt.Errorf("content node (%s) does not exist in %q", id, keg.Name)
		}
		if err := file.Edit(path); err != nil {
			return err
		}
		if err := MakeDex(keg.Path); err != nil {
			return err
		}
		return Publish(keg.Path)
	},
```

**Comment by VSngg** [comment]
Your instructions didn't work, however if I edit `go.mod` and update `choose` module to `v0.2.1` the program compiles successfully.

**Comment by BuddhiLW** [comment]
The issue is resolved. He updated the `mod.go`. Can you confirm it's working there? It's here.

**Comment by VSngg** [comment]
Everything is working. Closing the issue.
