### ISSUE TITLE
Embedded doc appeared faulty because I didn't have `export LESS=-r`

### ISSUE THREAD

**Issue by sderev** [rwxrob/keg#58]
I don't know all the history development, but from what I understood from your [Zettel#1712](https://github.com/rwxrob/zet/blob/2dbb831809bf6bab9a132311a69f8b42c63e534c/docs/1712/README.md), a hard coded check might be reconsidered for the installation process.

**This is how it renders without `export LESS=-r`:**

![image](https://user-images.githubusercontent.com/24412384/204089248-207562cb-496e-4d1c-a115-c59467a29792.png)

**Comment by sderev** [comment]
**Another recommendation could be made to users:**
adding the flag `-f` to `LESS` will disable this warning message when keg runs:

![image](https://user-images.githubusercontent.com/24412384/204090969-b60e76f2-a3bd-4afa-9e13-9d73684a48b5.png)

**Comment by rwxrob** [comment]
Yep, I fought with that too then learned about `export LESS=R` but don't know how many will know to do that. The `git` program gets around this somehow without ever complaining.
