### ISSUE TITLE
IsoDateFmt seems to be invalid

### ISSUE THREAD

**Issue by sderev** [rwxrob/keg#60]
The IsoDateFmt returns the local machine datetime and adds a 'Z' at the end, instead of returning true UTC as the 'Z' suffix implies.

https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)

**Comment by rwxrob** [comment]
Good catch. That's fixed now. Also had the minute wrong for the index listing in `kn latest`. Also fixed.
