### ISSUE TITLE
`keg last` and `keg latest` behavior feels odd to me: a suggestion

### ISSUE THREAD

**Issue by sderev** [rwxrob/keg#65]
At first, I thought `keg last` was supposed to return the last created node, but I was very confused to see that it always returned the penultimate node. Then, I carefully read the doc that says:
> show last n nodes **changed**

The thing is that second to last created node has not been technically *changed*. So why is it considered to be the **last** instead of the very true last created node?

Also `latest` is an alias of `last`. I feel like `last` could return the last created node*s*, whereas `latest` would return the *"last"* nodes that have been changed. Or maybe the inverse? I don't know. It's a semantic problem.

**Comment by rwxrob** [comment]
Yep, it behaved like that at one point. I agree. I'll make this change.
