### ISSUE TITLE
Add concurrent, stateful `grep`

### ISSUE THREAD

**Issue by rwxrob** [rwxrob/keg#75]
Although it probably needs to be its own composable bonzai stateful command branch, `grep` needs to be implemented with the following:

* Configurable concurrency (number of goroutines)
* Stateful, cacheable, pre-filter aggregations
* Full Go regular expression support (including Unicode code planes)
* Stateful priority preferences by keg (including followed, cached), and nodes

Later, we can *also* to FTS as a separate command.

**Comment by BuddhiLW** [comment]
At [BuddhiLW/keg-rearch](https://github.com/BuddhiLW/keg-search), I added the `-s` flag for `surrounding-context`. As we discussed yesterday, on stream.

Now, one can search passing a number of character one wants for context, from their match - this value serves for both left-right. The value will always respect the content-boundary condition - e.g., won't return errors if the surrounding-context-value would exceed the file-text size. Instead, it goes as far as possible. Worst case scenario (exceeding left and right) will return the hole file.

Furthermore, the seacher now loads the entire file. So, it would have problems regarding matching through line-breaking.

**Comment by rwxrob** [comment]
Very nice. We can add something like this (without the `getopt`-like dashes, of course). I'd like to add optional color hilighting, multiple matches per file, and optional colors file indicator with a colon as well, the regular stuff people expect having piped results to page.
